### ISSUE TITLE
Much awesome

### ISSUE THREAD

**Issue by chmac** [benbjohnson/thesecretlivesofdata#14]
Not an issue, just a quick note to say that this is freakin' awesome. The raft protocol explanation was fantastic. It's like the Khan Academy meets data. Clearly explains the protocol in a few short minutes in super simple terms. Thank you kindly for your inspiring work in this area. You rock.

**Comment by benbjohnson** [comment]
thanks! sorry for the delayed response! i'm working on some new ones but they'll be in video form on YouTube instead of JS. i'll post them here as they're ready:

https://www.youtube.com/channel/UCBnWMwyZH6s2S5fLiNp6QyQ

**Comment by joonas-fi** [comment]
I hope I'm not bothering by commenting on old issue, but I totally agree - much awesome!

I remember seeing this visualization a long time ago, and just like last week I tweeted that BoltDB is awesome. Then like a day ago I happened to stumble upon a Changelog (.com) podcast episode where you talked about Bolt, InfluxDB and TheSecretLivesOfData, and I didn't even realize that you were the same person who made this visualization. Huge props, dude! So many wow, much awesome.

**Comment by ryuheechul** [comment]
I also wanted to say the same thing and glad here's already an issue about it for me to be able to say something.
👏 Thanks for the great work and now I have much better understanding of how actually data can be consistent across different nodes with all kind of different scenario of failures.
