### ISSUE TITLE
Keyboard Navigation

### ISSUE THREAD

**Issue by benbjohnson** [benbjohnson/thesecretlivesofdata#3]
Add support for the right arrow key instead of requiring the user to constantly hit the "Continue" button.

/cc: @philips

**Comment by andybons** [comment]
Would also be nice to be able to go back as well (both using the arrow keys and the UI)

**Comment by benbjohnson** [comment]
@andybons Going back is a little tricky. The visualization uses [playback.js](https://github.com/benbjohnson/playback.js) which separates larger sections into frames and snapshots the underlying model whenever moving forward to new frames. Going back a whole section (i.e. a frame) is easy because I have the snapshotted model but moving back within a frame is currently impossible because the model changes.

Maybe I'll adjust playback.js to use immutable objects so I can easily make continuous snapshots.

**Comment by benbjohnson** [comment]
https://github.com/benbjohnson/playback.js/issues/1
https://github.com/benbjohnson/playback.js/issues/2

**Comment by andybons** [comment]
Gotcha. Sounds good!

**Comment by benbjohnson** [comment]
Fixed with 52377f11b0717711e813101c659489c4ea5bc49c.
