### ISSUE TITLE
May I use your visualization to teach students about raft consensus algorithms?

### ISSUE THREAD

**Issue by yaksoo39** [benbjohnson/thesecretlivesofdata#43]
Hi Ben.  I am preparing teaching materials as part of Samsung's effort to provide free to use education material.  I came across your most excellent visualization tool and hope to use it as part of my  curriculum.  Unfortunatley, Samsung's
policy prevents me from simply including links.  This is because many of the countries where the educatiion material will 
be provided often have very poor or no internet connections.  So, in order to use your visualization, I created a small video
of the visualization.  (Screen recording with me pushing the buttons).

Please let me know if I may use your materials in this manner, and if so, what type of copyright disclosure you would like me to present in the materials.

Thank you.

Henry Park

**Comment by benbjohnson** [comment]
Hi @yaksoo39. Yes, the visualization is free to share. You can change it or do anything with it, really. You can add attribution but you don't need to. I hope your students enjoy it!
