### ISSUE TITLE
Are there any plans to expand to Paxos and other Distributed Systems

### ISSUE THREAD

**Issue by ahmediq-git** [benbjohnson/thesecretlivesofdata#54]
Hi, wanted to say that I love the animations here for RAFT and it helped me understand it better when implementing it for my Distirbuted Systems course. Wanted to ask if there are any plans to make animations for perhaps Paxos or PBFT and other implementations of distributed systesm

**Comment by benbjohnson** [comment]
I'm currently working on some tooling to make these kinds of animations much easier to generate. I'd be up for doing Paxos and/or some kind of BFT in the future.

**Comment by ahmediq-git** [comment]
That sounds amazing! Is there any way I can contribute to or support the tooling project and other future projects of this kind?

**Comment by benbjohnson** [comment]
@ahmediq-git Thanks for the offer but nothing at the moment. Once I get it a little more stable then I'll open source it. I'll be posting work to this org eventually: https://github.com/secretlivesofdata

**Comment by ahmediq-git** [comment]
No worries at all! Looking forward to it becoming opensource and I have followed the Org aswell. All the very best!!
