### ISSUE TITLE
Raft leader election during network split

### ISSUE THREAD

**Issue by Scooletz** [benbjohnson/thesecretlivesofdata#8]
Isn't the leader elected by majority of all nodes? If so, why during the presentation the network partition allows to create two leaders in disjointed partitions.

**Comment by benbjohnson** [comment]
Only one leader can be elected per term. You can have two leaders for different terms but the leader of the older term cannot commit anything since there is a majority of nodes already at the higher term.

Does that make sense?

**Comment by Scooletz** [comment]
Yes it does. Once the first leader is elected, a partition can occur and he can be left with one follower. The rest of nodes can create majority and elect a new leader in new term.
Thx for clarification. I found it hard to see in the presentation.
